  const PRESETS_YOUTH = [
    {
      id: "sunset-lace",
      emoji: "🌇",
      title: "日落蕾丝回眸",
      desc: "窗边 · 强逆光 · I3",
      extra: "strong window rim light, body in soft shadow, plain sheer white curtains no print, half-lidded knowing gaze",
      picks: {
        combo: "combo-window-lace",
        intensity: "edge",
        act: "window-risk",
        imply: "i3",
        pose: "look-back",
        cloth: "lace-set",
        set: "window-city",
        light: "golden-hour",
        cam: "full-v",
        focus: "spine",
        expr: "knowing-lens",
        aes: "chunyu",
        hair: "longblack",
      },
    },
    {
      id: "mirror-shirt",
      emoji: "🪞",
      title: "镜前男友衫",
      desc: "自赏 · I2 单扣",
      extra: "mirror reflection matches pose exactly, one lower button only",
      picks: {
        combo: "combo-mirror-stretch",
        intensity: "pure-desire",
        act: "self-gaze",
        imply: "i2",
        pose: "mirror-stretch",
        cloth: "oversized-shirt",
        set: "bedroom-night",
        light: "bedside-tungsten",
        cam: "mirror-full",
        focus: "midriff",
        expr: "self-absorbed",
        aes: "chunyu",
      },
    },
    {
      id: "bed-soft",
      emoji: "🛏️",
      title: "床沿纯欲",
      desc: "侧坐 · 居家 I1",
      extra: "soft weight on one hip, feet or knees in frame",
      picks: {
        combo: "combo-bed-side-lie",
        intensity: "pure-desire",
        act: "solo-display",
        imply: "i1",
        pose: "bed-edge",
        cloth: "sleep-set",
        set: "bedroom-morning",
        light: "window-45",
        cam: "ms-v",
        focus: "collarbone",
        expr: "half-lidded",
        aes: "chunyu",
      },
    },
    {
      id: "sofa-phone",
      emoji: "📱",
      title: "沙发手机",
      desc: "懒刷 · 屏光",
      extra: "phone glow as key, casual not stiff",
      picks: {
        combo: "combo-sofa-phone",
        intensity: "pure-desire",
        act: "lazy-scroll",
        imply: "i1",
        pose: "sofa-curl",
        cloth: "cami-shorts",
        set: "sofa-day",
        light: "phone-screen",
        cam: "ms-v",
        focus: "thighs",
        expr: "sleepy",
        aes: "songchi",
      },
    },
    {
      id: "wet-bath",
      emoji: "🚿",
      title: "浴后湿发",
      desc: "蒸汽 · 锁骨",
      extra: "damp hair on neck, coverage locked",
      picks: {
        combo: "combo-bath-fog-mirror",
        intensity: "sensual-implied",
        act: "after-bath",
        imply: "i3",
        pose: "mirror-strap",
        cloth: "towel-wrap",
        set: "bath-steam",
        light: "steam-bath",
        cam: "mcu-collar",
        focus: "wet-hair",
        expr: "half-lidded",
        aes: "chunyu",
      },
    },
    {
      id: "jinyu-blind",
      emoji: "👔",
      title: "禁欲百叶",
      desc: "白衬衫 · 条纹光",
      extra: "mostly buttoned white shirt, cool restrained desire",
      picks: {
        combo: "combo-v-jinyu-blind",
        intensity: "pure-desire",
        act: "window-risk",
        imply: "i1",
        pose: "window-lean",
        cloth: "white-shirt",
        set: "sparse-window",
        light: "blind-stripes",
        cam: "ms-v",
        focus: "collarbone",
        expr: "qingleng",
        aes: "jinyu",
      },
    },
    {
      id: "bai-window",
      emoji: "🌙",
      title: "白月光窗",
      desc: "清冷可望",
      extra: "almost no smile, sparse pale room",
      picks: {
        combo: "combo-v-bai-window",
        intensity: "fresh",
        act: "window-risk",
        imply: "i0",
        pose: "window-lean",
        cloth: "white-shirt",
        set: "sparse-window",
        light: "morning-cool",
        cam: "neg-window",
        focus: "lips-gaze",
        expr: "qingleng",
        aes: "baiyueguang",
      },
    },
    {
      id: "softlife-coffee",
      emoji: "☕",
      title: "soft life 金辉",
      desc: "慢晨咖啡",
      extra: "coffee mug optional, lived-in soft morning",
      picks: {
        combo: "combo-softlife-coffee",
        intensity: "fresh",
        act: "golden-idle",
        imply: "i1",
        pose: "sofa-curl",
        cloth: "cream-knit",
        set: "cream-room",
        light: "golden-hour",
        cam: "ms-v",
        focus: "collarbone",
        expr: "sleepy",
        aes: "softlife",
        hair: "messy",
      },
    },
    {
      id: "hotel-robe",
      emoji: "🏨",
      title: "酒店浴袍",
      desc: "刚到 · 暧昧",
      extra: "travel bag far corner, quiet arrival",
      picks: {
        combo: "combo-hotel-arrival",
        intensity: "sensual-implied",
        act: "solo-display",
        imply: "i2",
        pose: "bed-edge",
        cloth: "satin-robe",
        set: "hotel-suite",
        light: "bedside-tungsten",
        cam: "ms-v",
        focus: "strap",
        expr: "knowing-lens",
        aes: "chunyu",
      },
    },
    {
      id: "coquette-bow",
      emoji: "🎀",
      title: "coquette 软欲",
      desc: "蕾丝边仍遮盖",
      extra: "soft bow detail, covered lace trim, not explicit",
      picks: {
        combo: "combo-coquette-bow-soft",
        intensity: "pure-desire",
        act: "self-gaze",
        imply: "i1",
        pose: "mirror-strap",
        cloth: "cami-shorts",
        set: "vanity-night",
        light: "window-45",
        cam: "xhs-cover",
        focus: "strap",
        expr: "tiny-smirk",
        aes: "coquette",
      },
    },
  ];
