# -*- coding: utf-8 -*-
"""公共维 L1–L5 + 三 skill 专属 · 联网/行业共识补全 2026-08-12 夜扩库。
来源内化：裙型百科(A/pencil/pleat/wrap/circle…) · 人像九光位 · 2025–26 亚发(wolf/hime/curtain/jellyfish/2in1) ·
K-beauty 妆壳 · 时尚姿族 · 成人静帧体位常青表。仅成人 18+。
"""
from __future__ import annotations


def I(id: str, label: str, en: str, group: str = "") -> dict:
    d = {"id": id, "label": label, "en": en}
    if group:
        d["group"] = group
    return d


# ═══════════════════════════════════════════════════════════════
# SUBJECT（L1 主体：子字段 = L2；细节 = L3）
# ═══════════════════════════════════════════════════════════════
ETH = [
    I("eastasian", "东亚默认★", "East Asian adult features", "L2人种"),
    I("chinese", "华人特征", "East Asian Chinese features non-stereotype", "L2人种"),
    I("japanese", "日本向", "Japanese adult or East Asian jp aesthetic", "L2人种"),
    I("korean", "韩国向", "Korean adult or East Asian kr aesthetic", "L2人种"),
    I("seasian", "东南亚", "Southeast Asian adult", "L2人种"),
    I("southasian", "南亚", "South Asian adult", "L2人种"),
    I("central_asian", "中亚", "Central Asian adult", "L2人种"),
    I("white", "白人/欧裔", "white European-appearing adult", "L2人种"),
    I("black", "黑人/非裔", "Black adult", "L2人种"),
    I("latine", "拉丁裔", "Latine Hispanic adult", "L2人种"),
    I("mena", "中东/北非", "Middle Eastern or North African adult", "L2人种"),
    I("mixed", "混血", "mixed heritage adult", "L2人种"),
    I("override", "用户原话", "ethnicity per user wording", "L2人种"),
]
AGE = [
    I("e20", "二十出头★", "in her early twenties", "L2年龄"),
    I("m20", "二十五上下", "in her mid-twenties", "L2年龄"),
    I("l20", "奔三前", "in her late twenties", "L2年龄"),
    I("t30", "轻熟/刚奔三", "early thirties mature-young adult", "L2年龄"),
    I("m30", "三十中段", "mid-thirties adult", "L2年龄"),
    I("l30", "三十末", "late thirties adult", "L2年龄"),
    I("mature", "四十+成熟点名", "mature adult forties+ as specified", "L2年龄"),
]
BODY = [
    I("slim", "修长★", "slender adult elongated neck long limbs", "L2体型"),
    I("average", "自然均称", "average natural adult build", "L2体型"),
    I("petite", "娇小成人", "petite adult frame adult facial proportions", "L2体型"),
    I("curvy", "曲线", "soft curvy adult full hips soft waist", "L2体型"),
    I("athletic", "运动体能", "toned athletic adult muscle definition soft", "L2体型"),
    I("busty", "丰胸焦点", "full bust priority natural adult proportions", "L2体型"),
    I("soft", "柔软微肉", "soft lightly plump adult not caricature", "L2体型"),
    I("hourglass", "沙漏", "hourglass adult waist-hip contrast", "L2体型"),
    I("rect", "直筒少曲线", "straighter athletic-slim adult line", "L2体型"),
    I("tall_slim", "高挑修长", "tall slender adult stature long legs", "L3体型读"),
]
SEX = [
    I("woman", "女性★", "adult woman", "L2性别"),
    I("man", "男性", "adult man", "L2性别"),
    I("androgynous", "中性呈现", "androgynous adult presentation", "L2性别"),
]
CAST = [
    I("solo", "单人★", "solo single adult subject", "L2人数"),
    I("duo", "双人", "two adults clear separation", "L2人数"),
    I("group", "群像3+", "group three+ one heroine sharp", "L2人数"),
    I("mirror", "镜中双身", "mirror double same person", "L2人数"),
    I("hand_only", "只露配角手", "secondary adult hand only", "L2人数"),
    I("partial_other", "配角半身出画", "secondary partial body soft", "L2人数"),
    I("implied_viewer", "隐含观看者", "implied viewer no second body", "L2人数"),
    I("couple", "情侣", "romantic couple equal or hero", "L2关系"),
    I("friends", "闺蜜友群", "friends cluster candid", "L2关系"),
    I("team", "团队同事", "team cluster occupational", "L2关系"),
    I("hero_focus", "主被摄优先", "heroine sharp others soft", "L2关系"),
    I("equal", "对等双人", "equal dual subject weight", "L2关系"),
    I("pov_self", "第一人称边肢", "POV self limb edge in frame", "L2关系"),
    I("yuri_pair", "双女互动", "two adult women interaction", "L2关系"),
    I("crowd_soft", "人群虚化背景", "soft bokeh crowd behind heroine", "L3人数"),
]

# 发型 L2 造型 + L3 刘海/态/色 + L4 质感
HAIR = [
    # L2 轮廓造型
    I("long_straight", "黑长直/丝滑长直★", "long sleek one-length straight hair", "L2造型"),
    I("long_layers", "长层次羽毛", "long layered feathered face-framing", "L2造型"),
    I("waves", "披肩微卷", "loose soft waves past shoulders", "L2造型"),
    I("beach_wave", "海滩波浪卷", "beach waves soft S-pattern", "L2造型"),
    I("wolf", "狼尾/狼剪", "wolf cut shaggy crown layered ends", "L2造型"),
    I("shag", "中长shag", "medium shag choppy lived-in layers", "L2造型"),
    I("butterfly", "蝴蝶剪", "butterfly cut face layers long back", "L2造型"),
    I("bob", "齐肩bob", "chin-length blunt or soft bob adult", "L2造型"),
    I("bob_textured", "层次bob", "textured piece-y bob volume", "L2造型"),
    I("bob_aline", "A线/内扣bob", "inverted A-line bob longer front", "L2造型"),
    I("lob", "锁骨发lob", "collarbone-length lob soft ends", "L2造型"),
    I("hime", "姬发成人", "hime cheek panels long back adult face", "L2造型"),
    I("hime_soft", "姬发软", "soft hime layers not blunt childlike", "L2造型"),
    I("two_in_one", "韩2-in-1 bob", "2-in-1 bob can wear up or down", "L2造型"),
    I("jellyfish", "水母切", "jellyfish cut short upper long lower", "L2造型"),
    I("high_layer_kr", "韩高层次", "Korean high-layered airy crown", "L2造型"),
    I("high_pony", "高马尾", "high voluminous ponytail wisps", "L2造型"),
    I("low_pony", "低马尾露颈", "low sleek ponytail clean nape", "L2造型"),
    I("messy_bun", "凌乱丸子", "messy bun face strands", "L2造型"),
    I("low_bun", "低髻/湿顺髻", "slick low bun or chignon", "L2造型"),
    I("half_up", "半扎", "soft half-up rest loose", "L2造型"),
    I("claw_half", "抓夹半完成", "claw-clip half-done pieces falling", "L2造型"),
    I("updo", "正式盘发", "elegant updo face-framing", "L2造型"),
    I("braid_soft", "软编/侧辫", "loose side braid adult", "L2造型"),
    I("wet", "湿发贴顺", "damp wet hair clinging neck glossy", "L2造型"),
    I("slick_back", "后梳湿顺中分", "slick wet center-part combed back", "L2造型"),
    I("messy", "睡乱披肩", "sleep-messy pillow-pressed hair", "L2造型"),
    I("c_curl", "C卷内扣", "C-curl ends soft bounce", "L2造型"),
    I("short_pixie", "短发/长pixie点名", "long pixie adult cool not child", "L2造型"),
    I("shoulder_soft", "及肩软直", "shoulder-length soft straight", "L2造型"),
    # L3 刘海
    I("bang_none", "无刘海露额", "clean forehead no bangs", "L3刘海"),
    I("bang_curtain", "窗帘刘海", "soft curtain bangs eyes visible", "L3刘海"),
    I("bang_wispy", "空气碎刘海", "wispy see-through airy bangs", "L3刘海"),
    I("bang_bottleneck", "瓶口刘海", "bottleneck fringe fuller center", "L3刘海"),
    I("bang_side", "侧分刘海", "side-swept bangs", "L3刘海"),
    I("bang_blunt", "齐刘海成人", "blunt brow bangs adult editorial", "L3刘海"),
    I("bang_micro", "微刘海点名", "micro bangs adult fashion not cute-child", "L3刘海"),
    I("part_center", "中分", "center part balanced", "L3分区"),
    I("part_side", "侧分", "soft side part volume one crown", "L3分区"),
    # L3 当帧状态
    I("state_loose", "披散自然", "hair down open over shoulders", "L3发态"),
    I("state_one_shoulder", "发覆一侧锁骨", "hair draped one collarbone", "L3发态"),
    I("state_tucked_ear", "一缕耳后", "one strand tucked behind ear neck long", "L3发态"),
    I("state_face_curtain", "发帘半脸", "hair curtain half covers one eye", "L3发态"),
    I("state_wind", "风动定格", "wind-caught strands mid-motion freeze", "L3发态"),
    I("state_ribbon", "丝带蝴蝶结", "satin ribbon or bow in hair", "L3发态"),
    I("state_grabbed", "被抓发根", "fist in hair at scalp", "L3发态"),
    I("state_over_face", "汗湿贴颊", "damp strands stuck to cheek", "L3发态"),
    # L3/L4 发色质感
    I("col_black", "发色自然黑★", "natural jet-black East Asian hair", "L3发色"),
    I("col_soft_black", "黑茶微棕光", "black-brown soft warm sheen", "L3发色"),
    I("col_dark_brown", "深棕", "dark chocolate brown", "L3发色"),
    I("col_warm_brown", "暖棕/茶棕", "warm tea brown", "L3发色"),
    I("col_ash", "灰棕冷棕", "cool ash brown", "L3发色"),
    I("col_milk_tea", "奶茶色", "milk-tea soft brown", "L3发色"),
    I("col_caramel", "焦糖balayage", "caramel balayage dark roots", "L3发色"),
    I("col_money", "面部money piece", "subtle money-piece face highlight", "L3发色"),
    I("col_ash_blonde", "浅亚麻点名", "soft ash blonde dark roots adult", "L3发色"),
    I("tex_glass", "水光发丝", "glass-like hair specular strands", "L4发质"),
    I("tex_matte", "雾面发", "matte soft hair no plastic shine", "L4发质"),
    I("tex_frizz_soft", "微毛躁真实", "soft natural flyaways lived-in", "L4发质"),
]

MAKEUP = [
    I("bare", "伪素/近素★", "no-makeup makeup sheer base soft brows bitten lip", "L2妆壳"),
    I("commute", "通勤淡妆★", "commute soft matte lips tidy brows even base", "L2妆壳"),
    I("id_neutral", "证件自然", "even natural earth tones soft liner", "L2妆壳"),
    I("kr_glass", "韩系水光", "dewy glass skin soft aegyo-sal gradient rose lip", "L2妆壳"),
    I("kr_3pt", "韩三点眉卧蚕唇", "straight soft brows defined aegyo-sal ombre lip", "L2妆壳"),
    I("jp_bite", "日系咬唇", "low-sat flush gradient bitten lip soft lashes", "L2妆壳"),
    I("douyin_soft", "抖音纯欲软", "glassy monochrome blush glossy gradient lip adult", "L2妆壳"),
    I("soft_glam", "软glam", "soft sculpt defined lashes satin lip", "L2妆壳"),
    I("warm_date", "约会暖妆", "warm dewy highlight glossy lip light contour", "L2妆壳"),
    I("qingleng", "清冷雾面", "cool mute flush matte soft lip low red", "L2妆壳"),
    I("mono_blush", "单色腮红妆", "same blush family lids and cheeks", "L2妆壳"),
    I("fox_soft", "轻狐狸眼", "elongated soft outer eye thin lifted liner", "L2妆壳"),
    I("red_lip", "经典红唇", "clean skin minimal eye classic red lip", "L2妆壳"),
    I("smoky_soft", "轻烟熏", "soft brown-black smoky blended", "L2妆壳"),
    I("flash_ready", "直闪耐拍", "stronger liner brow controlled highlight", "L2妆壳"),
    I("sport_sheer", "运动薄妆", "sheer SPF look fine sport sheen", "L2妆壳"),
    I("home_soft", "居家近素", "near bare moist lip home soft", "L2妆壳"),
    I("mama_born", "妈生感", "ma-saeng natural born soft brow lip", "L2妆壳"),
    I("dan_gan", "淡感妆", "ultra minimal presence makeup", "L2妆壳"),
    I("blur_lip", "模糊唇2026", "blurred soft-edge lip stain", "L2妆壳"),
    I("undereye_flush", "眼下腮红", "undereye flush soft aegyo zone", "L2妆壳"),
    I("butter_skin", "黄油皮原生", "butter-skin soft sheen native look", "L2妆壳"),
    I("qianjin", "千金妆", "refined qianjin clean luxe makeup", "L2妆壳"),
    I("latte", "拿铁暖妆", "latte warm brown-rose monochrome", "L2妆壳"),
    I("glazed", "釉面肌", "glazed donut skin high specular controlled", "L2妆壳"),
    I("ruined", "花妆泪妆", "smeared lipstick mascara tears wet", "L2妆壳"),
    I("stage_soft", "舞台淡化版", "stage readable makeup softened for still", "L2妆壳"),
    # L3 零件（拼进一句）
    I("part_aegyo", "件·卧蚕", "soft aegyo-sal under-eye fullness", "L3妆件"),
    I("part_gradient_lip", "件·渐变唇", "gradient lip darker center blurred edge", "L3妆件"),
    I("part_straight_brow", "件·直眉", "straight soft natural brows", "L3妆件"),
    I("part_horizontal_blush", "件·横扫腮", "horizontal blush mid-cheek", "L3妆件"),
    I("part_tightline", "件·内眼线浅", "thin tightline only", "L3妆件"),
    I("part_glass", "件·水光高光", "glass specular on high planes", "L3妆件"),
    I("part_mlbb", "件·豆沙雾唇", "MLBB muted rose matte lip", "L3妆件"),
]

EXPR = [
    I("soft_smile", "浅笑★", "soft closed or slight smile eyes gentle", "L2表情"),
    I("neutral", "中性证件", "neutral professional sharp eyes", "L2表情"),
    I("mute", "抿唇", "lips softly pressed calm", "L2表情"),
    I("cool", "冷眼酷", "direct cool eye contact minimal smile", "L2表情"),
    I("qingleng", "清冷少笑", "almost no smile cool distant", "L2表情"),
    I("laugh", "中途笑", "mid soft laugh candid imperfect", "L2表情"),
    I("focus_task", "专注任务", "gaze on phone book work", "L2表情"),
    I("away", "看远出画", "gaze off-frame into light street", "L2表情"),
    I("wind_squint", "风中微眯", "soft squint hair motion", "L2表情"),
    I("half_lidded", "半眯★", "half-lidded knowing eyes", "L2表情"),
    I("soft_bite", "轻咬下唇", "soft bite lower lip quiet", "L2表情"),
    I("knowing_lens", "盯镜头知情", "knowing gaze holds camera as watched", "L2表情"),
    I("sleepy", "刚醒睡意", "sleepy soft wake unfocused", "L2表情"),
    I("tiny_smirk", "极浅笑玩味", "tiny unhurried smirk", "L2表情"),
    I("self_gaze", "自赏镜中", "self-absorbed calm mirror focus", "L2表情"),
    I("confident", "自信有神", "confident clear eyes editorial", "L2表情"),
    I("candid", "抓拍无摆", "candid unposed natural face", "L2表情"),
    I("weary", "倦意", "weary soft tired adult eyes", "L2表情"),
    I("serene", "平静安宁", "serene calm peaceful face", "L2表情"),
    I("curious", "好奇微张", "curious soft parted lips", "L2表情"),
    I("windswept", "风中神情", "windswept alive expression", "L2表情"),
    I("bedroom_eyes", "卧室眼", "half-lidded inviting bedroom eyes", "L2分轨"),
    I("shocked_aroused", "撞见慌欲", "wide eyes flush parted lips", "L2分轨"),
    I("tears_pleasure", "快感泪", "watery eyes pleasure not horror", "L2分轨"),
    I("orgasm", "高潮脸", "unfocused mouth open brows knit", "L2分轨"),
    I("afterglow", "事后慵懒", "heavy lids soft spent bliss", "L2分轨"),
    I("ahegao", "阿黑颜点名", "rolled eyes tongue out drool adult only", "L2分轨"),
    I("fucked_silly", "被干傻脸点名", "empty bliss fucked-silly adult", "L2分轨"),
    I("performative", "舞台表演脸", "performative stage projection", "L2分轨"),
    I("editorial_blank", "走秀无表情", "blank editorial runway face", "L2分轨"),
    I("gaze_to_lens", "视线·镜头", "eyes to camera lens", "L3视线"),
    I("gaze_off", "视线·出画", "eyes off-frame", "L3视线"),
    I("gaze_down", "视线·垂眼", "eyes cast down", "L3视线"),
    I("gaze_partner", "视线·看对方", "eyes on partner", "L3视线"),
    I("gaze_mirror", "视线·镜中", "eyes to mirror self", "L3视线"),
    I("gaze_task", "视线·任务物", "eyes on task object", "L3视线"),
    I("gaze_light", "视线·看光", "eyes toward key light", "L3视线"),
]

# 衣着：L2 品类 + L3 裙/版型/长度/状态 + L4 鞋配 + L5 面料词
CLOTH = [
    # L2 大品类
    I("outer_coat", "外套/大衣", "long wool or fashion coat", "L2外搭"),
    I("outer_trench", "风衣", "classic trench belt soft", "L2外搭"),
    I("outer_puffer", "羽绒服/棉服", "puffer coat open or belted soft", "L2外搭"),
    I("blazer_suit", "西装/通勤套", "tailored blazer trousers or skirt suit", "L2外搭"),
    I("leather_jacket", "皮衣", "soft leather or faux jacket", "L2外搭"),
    I("denim_jacket", "牛仔外套", "denim jacket mid-wash", "L2外搭"),
    I("shirt_blouse", "衬衫/雪纺上衣", "button shirt or soft blouse", "L2上装"),
    I("tee_hoodie", "T恤/卫衣", "tee or clean hoodie", "L2上装"),
    I("knit_cardigan", "针织/开衫", "fine knit or open cardigan", "L2上装"),
    I("tank_cami", "背心/吊带上衣", "ribbed tank or cami top", "L2上装"),
    I("dress", "连衣裙★", "one-piece dress", "L2裙装"),
    I("skirt", "半身裙★", "separate skirt", "L2裙装"),
    I("pants", "裤装", "trousers tailored wide or slim", "L2下装"),
    I("denim", "牛仔裤/裙向", "denim jeans or denim skirt", "L2下装"),
    I("shorts", "短裤(成人)", "tailored or soft shorts mid-thigh adult", "L2下装"),
    I("sport", "运动套装", "matching athleisure set", "L2运动"),
    I("lounge", "家居完整装", "full loungewear clothed neat", "L2居家"),
    I("sleep", "睡衣/睡裙", "sleep set or nightgown", "L2居家"),
    I("robe", "浴袍/晨袍", "satin robe wrap", "L2居家"),
    I("slip", "吊带裙slip", "silk slip dress", "L2居家"),
    I("shirt_only", "仅大衬衫", "oversized shirt as dress", "L2居家"),
    I("cami_set", "吊带短裤套", "cami and soft shorts", "L2居家"),
    I("formal", "礼服/场合", "gown or formal dress", "L2场合"),
    I("old_money", "名媛静奢叠", "quiet luxury knit coat layers", "L2场合"),
    I("new_chinese", "新中式", "new Chinese aesthetic respectful", "L2场合"),
    I("swim", "泳装点名", "swimsuit user-requested", "L2特殊"),
    I("techwear", "机能装", "techwear shell layers", "L2特殊"),
    I("lingerie", "内衣套装", "lingerie set detailed straps", "L2特殊"),
    I("towel", "浴巾裹", "towel wrap coverage written", "L2特殊"),
    I("ol_set", "OL制服向", "office blouse skirt set", "L2特殊"),
    I("layer_ootd", "潮流层叠OOTD", "street layered OOTD 2-4 pieces", "L2特殊"),
    I("latex_leather", "乳胶/皮情趣", "latex or fetish leather shine", "L2特殊"),
    I("cos_costume", "COS套装", "recognizable cosplay adult", "L2特殊"),
    I("maid_nurse", "女仆护士兔女郎", "classic adult costume set", "L2特殊"),
    # L3 连衣裙版型
    I("dress_aline_midi", "连衣·A字中长", "A-line midi dress modest neckline", "L3连衣"),
    I("dress_bodycon", "连衣·包身", "bodycon dress adult tasteful", "L3连衣"),
    I("dress_wrap", "连衣·裹身", "wrap dress tied waist", "L3连衣"),
    I("dress_shirt", "连衣·衬衫裙", "shirt dress belted soft", "L3连衣"),
    I("dress_sweater", "连衣·毛衣裙", "sweater knit dress column", "L3连衣"),
    I("dress_slip_bias", "连衣·斜裁slip", "bias-cut silk slip dress", "L3连衣"),
    I("dress_fit_flare", "连衣·收腰伞摆", "fit-and-flare dress", "L3连衣"),
    I("dress_empire", "连衣·高腰", "empire waist dress soft", "L3连衣"),
    I("dress_mermaid", "连衣·鱼尾", "mermaid silhouette gown-dress", "L3连衣"),
    I("dress_tiered", "连衣·层层", "tiered ruffle dress adult", "L3连衣"),
    I("dress_knit_column", "连衣·针织直筒", "column knit midi dress", "L3连衣"),
    # L3 半裙版型（行业裙种补全）
    I("skirt_aline", "半裙·A字", "A-line skirt flattering flare", "L3半裙"),
    I("skirt_pencil", "半裙·包臀铅笔", "pencil skirt knee sleek", "L3半裙"),
    I("skirt_pleat", "半裙·百褶", "pleated skirt fold texture", "L3半裙"),
    I("skirt_accordion", "半裙·手风琴褶", "accordion fine pleats", "L3半裙"),
    I("skirt_wrap", "半裙·裹身", "wrap skirt adjustable waist", "L3半裙"),
    I("skirt_circle", "半裙·圆裙/太阳裙", "circle full skirt volume", "L3半裙"),
    I("skirt_godet", "半裙·插片摆", "godet panel flare skirt", "L3半裙"),
    I("skirt_balloon", "半裙·花苞", "balloon volume skirt fashion", "L3半裙"),
    I("skirt_skater", "半裙·滑板伞", "skater flare short-to-midi", "L3半裙"),
    I("skirt_slip", "半裙·丝质slip", "bias silk slip skirt", "L3半裙"),
    I("skirt_cargo", "半裙·工装", "cargo skirt pockets soft", "L3半裙"),
    I("skirt_tennis", "半裙·网球(内衬)", "tennis mini shorts underneath athletic", "L3半裙"),
    I("skirt_denim", "半裙·牛仔", "denim skirt mid or mini adult", "L3半裙"),
    I("skirt_leather", "半裙·皮", "leather skirt structured", "L3半裙"),
    I("skirt_asym", "半裙·不对称", "asymmetric hem modern", "L3半裙"),
    I("skirt_tiered", "半裙·层层", "tiered skirt soft volume", "L3半裙"),
    I("skirt_slit", "半裙·开衩", "high slit skirt freeze", "L3半裙"),
    I("skirt_tulip", "半裙·郁金香", "tulip draped skirt", "L3半裙"),
    I("skirt_peg", "半裙·泡泡/茧型", "pegged or cocoon soft volume", "L3半裙"),
    # L3 长度
    I("len_mini", "长度·mini短", "mini length adult proportions", "L3长度"),
    I("len_knee", "长度·及膝", "knee length classic", "L3长度"),
    I("len_midi", "长度·midi中长★", "midi mid-calf elegant", "L3长度"),
    I("len_maxi", "长度·maxi长", "maxi floor-grazing", "L3长度"),
    I("len_tea", "长度·茶长", "tea length below knee", "L3长度"),
    I("waist_high", "腰线·高腰", "high waist line clear", "L3腰线"),
    I("waist_mid", "腰线·中腰", "mid waist natural", "L3腰线"),
    I("waist_low", "腰线·低腰点名", "low waist as requested adult", "L3腰线"),
    # L3 裤
    I("pants_wide", "裤·阔腿", "high-waist wide-leg trousers", "L3裤"),
    I("pants_straight", "裤·直筒", "straight crease trousers", "L3裤"),
    I("pants_slim", "裤·修身", "slim tailored trousers", "L3裤"),
    I("pants_cargo", "裤·工装", "soft cargo pants not costume", "L3裤"),
    I("jeans_wide", "牛仔·阔腿", "high-waist wide-leg denim", "L3裤"),
    I("jeans_straight", "牛仔·直筒", "straight mid-wash jeans", "L3裤"),
    I("jeans_slim", "牛仔·修身", "slim or skinny jeans adult", "L3裤"),
    # L3 状态
    I("st_full", "状态·整齐★", "fully clothed neat complete", "L3状态"),
    I("st_relaxed", "状态·居家随意", "relaxed home dress unfussy", "L3状态"),
    I("st_layer_open", "状态·外套敞开", "outer layer open waist readable", "L3状态"),
    I("st_strap_slip", "状态·肩带滑落", "thin strap slipped one shoulder", "L3状态"),
    I("st_few_buttons", "状态·少扣领开", "few buttons open collar shadow", "L3状态"),
    I("st_one_button", "状态·只扣一颗", "single lower button only", "L3状态"),
    I("st_hem_up", "状态·下摆掀卷", "hem lifted or shirt hem up midriff", "L3状态"),
    I("st_skirt_hike", "状态·裙摆提起", "skirt hem lightly held or hiked", "L3状态"),
    I("st_half_off", "状态·半褪", "half-undressed heights written", "L3状态"),
    I("st_sheer_wet", "状态·湿透贴肤", "wet cling translucent edge", "L3状态"),
    I("st_off_shoulder", "状态·露肩", "one or both shoulders bare intentional", "L3状态"),
    I("st_unzipped", "状态·拉链半开", "zipper half open controlled", "L3状态"),
    # L4 鞋
    I("foot_sneaker", "鞋·运动鞋", "clean sneakers", "L4鞋"),
    I("foot_chunky", "鞋·老爹鞋", "chunky sneakers", "L4鞋"),
    I("foot_loafer", "鞋·乐福", "leather loafers", "L4鞋"),
    I("foot_maryjane", "鞋·玛丽珍", "Mary Jane flats or low heel", "L4鞋"),
    I("foot_ballet", "鞋·芭蕾平底", "ballet flats", "L4鞋"),
    I("foot_boot_ankle", "鞋·短靴", "ankle boots", "L4鞋"),
    I("foot_boot_knee", "鞋·过膝靴", "knee-high boots under coat", "L4鞋"),
    I("foot_heel_kit", "鞋·中跟", "low kit heels editorial", "L4鞋"),
    I("foot_heel_stiletto", "鞋·细高跟", "stiletto heels", "L4鞋"),
    I("foot_sandal", "鞋·凉鞋", "simple sandals summer", "L4鞋"),
    I("foot_mule", "鞋·穆勒", "mules soft", "L4鞋"),
    I("foot_bare", "鞋·裸足", "bare feet", "L4鞋"),
    I("foot_socks", "鞋·袜/丝袜可见", "socks or sheer hosiery visible", "L4鞋"),
    # L4 配饰
    I("acc_glasses", "配·眼镜", "thin metal or clear frames", "L4配"),
    I("acc_sunglass", "配·墨镜", "sunglasses on face or hair", "L4配"),
    I("acc_hoop", "配·小圈耳环", "small gold hoops", "L4配"),
    I("acc_chain", "配·细链", "delicate chain necklace", "L4配"),
    I("acc_choker", "配·颈圈/项圈装饰", "thin choker fashion", "L4配"),
    I("acc_watch", "配·表", "slim watch", "L4配"),
    I("acc_hat", "配·帽", "beret or cap", "L4配"),
    I("acc_scarf", "配·丝巾", "silk scarf neck or bag", "L4配"),
    I("acc_belt", "配·细腰带", "thin belt waist define", "L4配"),
    I("acc_mask", "配·口罩", "mask on or pulled chin", "L4配"),
    I("acc_earphone", "配·耳机", "earbuds or over-ear", "L4配"),
    I("acc_none", "配·无主配", "no statement accessories", "L4配"),
    # L5 面料/质感词（写作挂靠）
    I("fab_silk", "料·丝光", "silk sheen drape", "L5面料"),
    I("fab_chiffon", "料·雪纺", "chiffon translucent layers SFW", "L5面料"),
    I("fab_cotton", "料·棉质哑光", "cotton matte soft", "L5面料"),
    I("fab_wool", "料·羊毛垂感", "wool drape heavy soft", "L5面料"),
    I("fab_denim", "料·牛仔纹理", "denim grain visible", "L5面料"),
    I("fab_knit", "料·针织罗纹", "knit rib texture", "L5面料"),
    I("fab_lace", "料·蕾丝", "lace pattern delicate", "L5面料"),
    I("fab_satin", "料·缎面", "satin gloss soft", "L5面料"),
    I("fab_leather", "料·皮革粒面", "leather soft grain", "L5面料"),
    I("fab_sheer", "料·薄透(非裸)", "sheer fabric over lining", "L5面料"),
]

POSE = [
    I("stand_weight", "站·重心后脚★", "weight back foot free knee soft", "L2站"),
    I("stand_scurve", "站·S线", "soft S-curve editorial", "L2站"),
    I("stand_power", "站·气场", "upright power shoulders square", "L2站"),
    I("stand_contrapposto", "站·对立式", "contrapposto classical weight shift", "L2站"),
    I("stand_3q", "站·3/4身", "three-quarter body to camera", "L2站"),
    I("stand_profile", "站·侧面干净", "clean profile full body", "L2站"),
    I("stand_hand_hip", "站·手叉腰", "hand on hip soft", "L2站"),
    I("stand_hands_up_soft", "站·柔抬手", "arms softly raised fashion", "L2站"),
    I("walk_midstride", "走·中步★", "mid-stride freeze heel down", "L2走"),
    I("walk_to_cam", "走·朝镜头", "walking toward camera mid-step", "L2走"),
    I("walk_away", "走·背影回眸", "walk away look back", "L2走"),
    I("lean", "靠·墙栏45°", "lean wall three-quarter arm gap", "L2靠"),
    I("lean_twist", "靠·拧身", "lean and torso twist", "L2靠"),
    I("lean_forward_waist", "靠·腰前倾", "lean forward from waist slimming", "L2靠"),
    I("over_shoulder", "回眸过肩", "look back over shoulder chin off neck", "L2靠"),
    I("pocket", "插袋松弛", "hands in pockets shoulders drop", "L2站"),
    I("sit_edge", "坐·沿", "perch seat edge spine long", "L2坐"),
    I("sit_cross", "坐·交腿", "legs crossed toe soft", "L2坐"),
    I("sit_forward_elbow", "坐·前倾托肘", "lean forward elbows knees", "L2坐"),
    I("sit_one_knee", "坐·一膝抬", "one knee up seated", "L2坐"),
    I("sit_stairs", "坐·台阶", "sit stairs asymmetric feet", "L2坐"),
    I("sit_floor", "坐·地成人", "floor sit knees soft adult modest", "L2坐"),
    I("sit_chair_back", "坐·反骑椅背", "chair backwards arms on back", "L2坐"),
    I("perch", "半坐搭靠", "hip perch table bar edge", "L2坐"),
    I("mirror_self", "镜前姿", "full-length mirror three-quarter", "L2镜床"),
    I("lie_side", "侧卧", "side-lying knees soft", "L2镜床"),
    I("lie_back", "仰躺半躺", "reclined soft arch", "L2镜床"),
    I("lie_prone", "俯卧点名", "prone on belly adult", "L2镜床"),
    I("bed_edge", "床沿坐/前倾", "bed edge sit lean waist", "L2镜床"),
    I("stretch", "伸展定格", "full-body stretch freeze", "L2镜床"),
    I("crouch", "蹲低姿", "fashion crouch compact", "L2其它"),
    I("kneel", "跪姿族", "kneeling skill-dependent openness", "L2其它"),
    I("hand_face", "托腮拨发", "chin hand or hair tuck simple", "L2其它"),
    I("frame_face", "轻框脸", "soft L-hands frame face", "L2其它"),
    I("task_work", "任务功能姿", "body to task hands mid-work", "L2其它"),
    I("athletic", "运动发力", "athletic stance lunge support clear", "L2其它"),
    I("yoga_asana", "瑜伽体式", "yoga asana supports clear", "L2其它"),
    I("dance_line", "舞蹈延伸", "dance line supporting leg clear", "L2其它"),
    I("wall_step", "离墙一步侧", "one step off wall side light", "L2其它"),
    I("window_pose", "窗边站坐", "at window sill stand or sit", "L2其它"),
    I("hem_twirl", "裙摆转圈定格", "twirl freeze skirt mid-flare", "L3细姿"),
    I("hem_hold", "轻提裙摆", "light hold dress hem mid-step", "L3细姿"),
    I("chin_hand_table", "桌边托腮", "chin hand cafe table", "L3细姿"),
    I("peace_low", "低位比耶", "peace near jaw chest adult soft", "L3细姿"),
    I("bag_strap", "握包带", "hand on bag strap shoulder", "L3细姿"),
    I("collar_bone_hand", "手近锁骨", "hand elegant near collarbone", "L3细姿"),
    I("door_peek", "门框探身", "half body doorway lean", "L3细姿"),
    I("crosswalk", "斑马线中步", "crosswalk mid-stride", "L3细姿"),
]

PROP = [
    I("none", "空手★", "hands free pocket or hair tuck", "L2道具"),
    I("phone", "手机", "phone natural hold screen toward or away", "L2道具"),
    I("cup_drink", "杯/咖啡", "ceramic cup both hands", "L2道具"),
    I("boba", "奶茶", "boba cup straw optional chest height", "L2道具"),
    I("bottle", "水瓶/冰美式", "tall bottle or iced drink", "L2道具"),
    I("bag_tote", "托特包", "canvas tote strap", "L2道具"),
    I("bag_shoulder", "肩包/腋下包", "shoulder or baguette under arm", "L2道具"),
    I("luggage", "行李箱", "upright suitcase handle", "L2道具"),
    I("book", "书", "book half-open chest or lap", "L2道具"),
    I("magazine", "杂志", "magazine open or rolled", "L2道具"),
    I("flower", "花束", "bouquet stems waist blooms readable", "L2道具"),
    I("flower_single", "单枝花", "single stem near face not covering eyes", "L2道具"),
    I("umbrella", "伞", "umbrella canopy or closed handle", "L2道具"),
    I("camera", "相机", "camera strap neck hands light", "L2道具"),
    I("instant", "拍立得", "instant print looking down", "L2道具"),
    I("keys", "钥匙", "keys at hip", "L2道具"),
    I("food", "小吃/甜筒", "skewer or ice cream adult", "L2道具"),
    I("laptop", "笔电", "laptop cafe mid-type freeze", "L2道具"),
    I("tool_work", "职业工具", "work tool mid-task", "L2道具"),
    I("sport_gear", "球拍/垫/盔", "racket mat helmet hip", "L2道具"),
    I("sheet_clutch", "抓床单", "hands clutch sheet", "L2道具"),
    I("curtain", "拉帘", "hand draws sheer curtain", "L2道具"),
    I("railing", "扶栏杆", "hand on rail", "L2道具"),
    I("toy_adult", "成人玩具点名", "adult toy user-requested", "L2道具"),
    I("restraint", "绳铐项圈", "rope cuff collar as prop", "L2道具"),
    I("vibe", "振动棒点名", "vibrator wand in frame", "L2道具"),
    I("mirror_phone", "镜前自拍手机", "phone in mirror selfie arm", "L2道具"),
]

SET = [
    I("street_city", "街/城★", "city sidewalk architecture lines", "L2城"),
    I("street_alley", "巷弄Citywalk", "narrow alley citywalk soft", "L2城"),
    I("metro_transit", "地铁站台", "metro platform handhold car", "L2城"),
    I("crosswalk_night", "雨夜斑马线", "rain crosswalk reflections", "L2城"),
    I("cafe", "咖啡/书咖", "cafe window seat cup wood", "L2城"),
    I("shop_third", "探店综合", "third-place shop interior", "L2城"),
    I("bookstore", "书店", "tall shelves spines ladder", "L2城"),
    I("flower_shop", "花店", "flower buckets glass green", "L2城"),
    I("convenience", "便利店夜", "fluorescent aisle fridge night door", "L2城"),
    I("laundromat", "洗衣房", "washer row seats soft light", "L2城"),
    I("cinema_lobby", "影院大堂", "cinema lobby posters lounge", "L2城"),
    I("mall_atrium", "商场中庭", "mall atrium escalator glass", "L2城"),
    I("night_neon", "夜霓虹", "neon mix wet street", "L2城"),
    I("night_market", "夜市", "night market stall steam crowd bokeh", "L2城"),
    I("rooftop", "天台", "rooftop rail skyline", "L2城"),
    I("parking", "停车场边缘", "parking concrete columns car bokeh", "L2城"),
    I("indoor_home", "家·客厅卧室", "home sofa bed soft interior", "L2室内"),
    I("bedroom", "卧室", "bedroom rumpled sheets lamp", "L2室内"),
    I("hotel", "酒店套房★", "hotel tungsten bed luggage keycard", "L2室内"),
    I("love_hotel", "情趣酒店", "love hotel LED mirror colored light", "L2室内"),
    I("bathroom", "浴室", "bathroom steam tile fog mirror", "L2室内"),
    I("shower", "淋浴间", "shower tile water streams", "L2室内"),
    I("window_sill", "窗边专场", "window sill city bokeh", "L2室内"),
    I("bay_window", "飘窗", "bay window cushion daylight", "L2室内"),
    I("vanity", "梳妆台", "vanity mirror warm bulbs", "L2室内"),
    I("kitchen", "厨房台沿", "kitchen counter morning window", "L2室内"),
    I("studio", "棚/无缝", "studio seamless paper", "L2室内"),
    I("office", "办公职场", "office glass corridor night", "L2室内"),
    I("library", "图书馆成人", "library stacks desk lamp adult", "L2室内"),
    I("gym_sport", "健身房", "gym mirror rack", "L2运动"),
    I("pool_deck", "泳池甲板", "pool deck water shimmer", "L2运动"),
    I("dance_studio", "练舞房", "dance studio wall mirror", "L2运动"),
    I("nature_outdoor", "自然户外", "nature trail forest light", "L2户外"),
    I("beach", "海边", "beach sand sea horizon", "L2户外"),
    I("landmark_travel", "旅拍地标", "travel landmark scale", "L2户外"),
    I("garden_cn", "中式园林", "Chinese garden lattice pond", "L2户外"),
    I("campus_adult", "校园成人", "adult campus lawn library", "L2户外"),
    I("stage_theater", "舞台", "stage spotlight black surround", "L2户外"),
    I("car_interior", "车内", "car interior steamed glass", "L2特殊"),
    I("balcony_rooftop", "阳台", "balcony rail dusk", "L2特殊"),
    I("airport", "机场", "airport glass boards luggage", "L2特殊"),
    I("elevator", "电梯镜", "elevator mirror harsh light", "L2特殊"),
    I("changing_room", "更衣间", "changing room lockers door", "L2特殊"),
    I("onsen", "温泉木風呂", "onsen wood steam night", "L2特殊"),
    I("fantasy_space", "幻想场", "fantasy sanctum magic light", "L2特殊"),
    I("dungeon_soft", "轻调教室", "soft dungeon elegant dark not gore", "L2特殊"),
]

LIGHT = [
    I("window_soft", "窗光软45°★", "window key 45 soft catchlights", "L2自然"),
    I("window_back", "窗逆光轮廓", "window backlight hair rim face filled", "L2自然"),
    I("overcast", "阴天平光", "overcast soft even gentle", "L2自然"),
    I("golden", "黄金时刻", "golden hour warm side long shadow", "L2自然"),
    I("blue_hour", "蓝调时刻", "blue hour cool ambient", "L2自然"),
    I("open_shade", "开敞阴影", "open shade soft outdoor", "L2自然"),
    I("dappled", "树荫斑驳", "dappled leaf light", "L2自然"),
    I("tungsten", "钨丝暖灯★", "warm tungsten bedside practical", "L2实用"),
    I("practical_lamp", "现场台灯", "one practical lamp deep falloff", "L2实用"),
    I("neon_mix", "霓虹混光", "neon rim mixed color", "L2实用"),
    I("screen_glow", "屏/手机冷光", "phone screen cool under-face", "L2实用"),
    I("steam_diffuse", "蒸汽漫射", "steam humid diffusion", "L2实用"),
    I("candle_soft", "烛光柔", "candle warm flicker soft", "L2实用"),
    I("fluorescent", "荧光冷白", "fluorescent cool narrative", "L2实用"),
    I("clamshell", "蚌式美妆", "clamshell beauty key plus fill below", "L2棚"),
    I("butterfly", "蝶形/派拉蒙", "butterfly paramount nose shadow", "L2棚"),
    I("loop", "环形光", "loop nose shadow soft cheek", "L2棚"),
    I("rembrandt", "伦勃朗", "Rembrandt cheek light triangle", "L2棚"),
    I("split", "分割光", "split light half face drama", "L2棚"),
    I("rim", "轮廓/逆光缘", "rim backlight separation", "L2棚"),
    I("cross", "交叉光", "cross lighting dual sides", "L2棚"),
    I("short_light", "短光显瘦", "short lighting face slim three-quarter", "L2棚"),
    I("broad_light", "宽光", "broad lighting open face", "L2棚"),
    I("hard_side", "硬侧光", "hard side light texture", "L2棚"),
    I("softbox_studio", "棚柔光", "large softbox studio key", "L2棚"),
    I("beauty_dish", "美人碟", "beauty dish specular control", "L2棚"),
    I("flash_on", "直闪硬", "hard on-camera flash punchy", "L2棚"),
    I("flash_bounce", "跳闪柔", "bounced flash soft ceiling", "L2棚"),
    I("gel_color", "色胶互补", "gel color accent complementary", "L2棚"),
    I("spotlight_stage", "舞台追光", "spotlight deep black surround", "L2棚"),
    I("high_key", "高键", "high-key bright clean minimal shadow", "L2棚"),
    I("low_key", "低调亲密", "low-key deep shadows intimate", "L2棚"),
    I("fake_window", "假窗影", "fake window gobo shadow pattern", "L3光效"),
    I("blind_stripe", "百叶条纹", "blind stripe shadow pattern", "L3光效"),
    I("god_rays", "丁达尔/光束", "volumetric god rays soft", "L3光效"),
    I("under_light", "底光慎用", "under-lighting dramatic rare", "L3光效"),
]

CAM = [
    I("ewide", "超远环境", "extreme wide tiny figure environment", "L2景别"),
    I("full", "全身★", "full body feet in frame", "L2景别"),
    I("cowboy", "牛仔景", "cowboy mid-thigh up", "L2景别"),
    I("medium", "中景", "medium waist-up", "L2景别"),
    I("mcu", "中近景MCU★", "medium close-up chest face", "L2景别"),
    I("cu", "近景脸", "close-up face", "L2景别"),
    I("ecu", "局部极近", "extreme close-up detail", "L2景别"),
    I("eye", "平视★", "eye-level camera", "L2角度"),
    I("low", "仰拍", "slight low angle elongated limbs", "L2角度"),
    I("high", "俯拍", "slight high angle face-friendly", "L2角度"),
    I("dutch", "荷兰角慎", "dutch tilt sparse use", "L2角度"),
    I("topdown", "顶视", "top-down overhead", "L2角度"),
    I("ot_s", "过肩", "over-the-shoulder framing", "L2角度"),
    I("ar_23", "画幅2:3", "vertical 2:3", "L2画幅"),
    I("ar_34", "画幅3:4★", "vertical 3:4 cover", "L2画幅"),
    I("ar_916", "画幅9:16", "vertical 9:16 shorts", "L2画幅"),
    I("ar_32", "画幅3:2横", "horizontal 3:2", "L2画幅"),
    I("ar_169", "画幅16:9", "horizontal 16:9", "L2画幅"),
    I("ar_11", "画幅1:1", "square 1:1", "L2画幅"),
    I("lens_24", "焦感24环境", "24mm environment wide", "L3焦段"),
    I("lens_35", "焦感35故事", "35mm story environmental", "L3焦段"),
    I("lens_50", "焦感50标准", "50mm natural perspective", "L3焦段"),
    I("lens_85", "焦感85美妆★", "85mm portrait compression beauty", "L3焦段"),
    I("lens_135", "焦感135压缩", "135mm tight compression", "L3焦段"),
    I("dof_shallow", "浅景深", "shallow depth of field bokeh", "L3光学"),
    I("dof_deep", "深景深", "deep focus environment sharp", "L3光学"),
    I("comp_thirds", "构图三分", "rule of thirds", "L3构图"),
    I("comp_center", "构图居中", "centered subject", "L3构图"),
    I("comp_neg", "构图负空间", "negative space breath", "L3构图"),
    I("comp_frame", "框中框", "frame within frame", "L3构图"),
    I("comp_leading", "引导线", "leading lines to subject", "L3构图"),
    I("comp_vertical", "竖屏分区", "vertical upper mid lower zones", "L3构图"),
    I("comp_foot", "留脚空间", "foot room full body", "L3构图"),
    I("comp_junction", "下三分结合部", "junction in lower third erotic", "L3构图"),
]

GRADE = [
    I("natural", "自然真色★", "natural true color restrained", "L2调色"),
    I("jp_cream", "日系奶油", "low-sat cream-green airy highlights", "L2调色"),
    I("kr_clean", "韩系干净亮", "clean bright midtones fresh skin", "L2调色"),
    I("qingleng", "清冷青灰", "cool muted cyan-gray low contrast", "L2调色"),
    I("portra", "胶片Portra肤", "Portra-like warm skin soft grain", "L2调色"),
    I("cine_soft", "电影青橙轻", "subtle teal shadows warm skin", "L2调色"),
    I("bw", "黑白", "rich midtones deep blacks", "L2调色"),
    I("bw_highcon", "高反差黑白", "high contrast black white", "L2调色"),
    I("flash_pop", "直闪高反差", "punchy flash vivid ambient", "L2调色"),
    I("ccd", "CCD数码感", "CCD digital snapshot look", "L2调色"),
    I("neon_night", "夜霓虹溢色", "neon color bleed night", "L2调色"),
    I("old_money", "静奢克制", "clean neutral restrained sat", "L2调色"),
    I("iphone", "手机HDR", "natural HDR phone look", "L2调色"),
    I("warm_sunset", "暖夕", "warm sunset amber", "L2调色"),
    I("cool_mute", "冷雾低饱和", "cool mute foggy low sat", "L2调色"),
    I("pastel", "粉彩低对比", "pastel low contrast soft", "L2调色"),
    I("moody_dark", "暗调情绪", "moody dark crushed blacks", "L2调色"),
    I("bleach", "过曝空气", "slight overexpose airy bleach", "L2调色"),
    I("anime_cel", "二次元平涂", "anime cel clean light saturated", "L2调色"),
    I("none", "不强调", "no strong grade stated", "L2调色"),
    I("grain_soft", "轻颗粒", "soft film grain overlay", "L3质感"),
    I("halation", "轻halation", "gentle highlight halation", "L3质感"),
]

# ── 专属 Figure ───────────────────────────────────────────────────
FIGURE_ZONE = [
    I("A", "A 商业时尚", "commercial fashion editorial zone", "专属大区"),
    I("B", "B 纪实环境★", "documentary environmental street zone", "专属大区"),
    I("C", "C 运动体能", "sports athletic body zone", "专属大区"),
    I("D", "D 表演身体", "dance stage performance zone", "专属大区"),
    I("E", "E 职业身份", "occupational portrait zone", "专属大区"),
    I("F", "F 艺术观念", "fine art figure conceptual zone", "专属大区"),
    I("G", "G 生活关系", "lifestyle travel relationship zone", "专属大区"),
    I("H", "H 特殊媒介", "underwater aerial special medium zone", "专属大区"),
    I("I", "I 私房室内点名", "soft SFW boudoir user-requested only", "专属大区"),
]

# ── 专属 Youth ──────────────────────────────────────────────────
YOUTH_INTENSITY = [
    I("fresh", "更清新", "fresh light implication", "专属尺度"),
    I("pure-desire", "纯欲默认★", "pure-desire sensual implied", "专属尺度"),
    I("sensual-implied", "更暧昧", "sensual-implied bolder non-explicit", "专属尺度"),
    I("edge", "擦边上限", "edge towel lingerie still covered", "专属尺度"),
]
YOUTH_ACT = [
    I("self-gaze", "对镜自赏", "mirror self-gaze", "专属行为"),
    I("solo-display", "独处展示", "solo display to lens", "专属行为"),
    I("after-bath", "浴后", "after-bath damp", "专属行为"),
    I("lazy-scroll", "懒刷手机", "lazy phone scroll", "专属行为"),
    I("stretch", "伸展", "body stretch freeze", "专属行为"),
    I("window-risk", "窗边风险★", "window-risk half-open city", "专属行为"),
    I("golden-idle", "黄金闲适", "golden idle sofa", "专属行为"),
    I("post-rehearsal", "练后", "post-rehearsal sweat rest", "专属行为"),
    I("night-routine", "夜routine", "night skincare routine freeze", "专属行为"),
    I("morning-wake", "晨起", "morning wake sheet", "专属行为"),
]
YOUTH_IMPLY = [
    I("i0", "I0 完整休闲", "full casual desire in eyes light", "专属I级"),
    I("i1", "I1 居家随意★", "loose home slight strap slip", "专属I级"),
    I("i2", "I2 半敞", "half-open buttons hem up", "专属I级"),
    I("i3", "I3 浴巾内衣轮廓", "towel lingerie outline still covered", "专属I级"),
]
YOUTH_FOCUS = [
    I("collarbone", "锁骨颈★", "collarbones neck highlight", "专属暗示"),
    I("midriff", "腰腹", "midriff waist hollow", "专属暗示"),
    I("thighs", "大腿缘", "thigh edge fabric bite", "专属暗示"),
    I("strap", "肩带", "slipped strap unreadjusted", "专属暗示"),
    I("wet_hair", "湿发贴颈", "wet hair on neck", "专属暗示"),
    I("lips_gaze", "唇与视线", "lips and gaze tension", "专属暗示"),
    I("spine_arch", "脊线反弓", "soft spine arch", "专属暗示"),
    I("nape", "后颈", "nape hairline soft", "专属暗示"),
    I("underboob_edge", "胸下缘阴影", "underbust shadow still covered", "专属暗示"),
]
YOUTH_AES = [
    I("chunyu", "纯欲壳★", "chunyu pure-desire shell", "专属美学"),
    I("baiyueguang", "白月光", "baiyueguang distant soft", "专属美学"),
    I("jinyu", "禁欲衬衫", "jinyu restrained white shirt", "专属美学"),
    I("coquette", "coquette", "coquette bow lace soft", "专属美学"),
    I("vanilla", "Vanilla奶油", "vanilla cream neutral", "专属美学"),
    I("softlife", "soft life", "soft life golden slow", "专属美学"),
    I("qingleng", "清冷", "qingleng cool sparse", "专属美学"),
    I("office_siren", "加班软欲", "office siren soft overtime", "专属美学"),
    I("clean_girl", "Clean Girl私密", "clean girl wet hair intimate", "专属美学"),
    I("digicam", "digicam直闪", "digicam y2k hard flash", "专属美学"),
    I("balletcore", "芭蕾核心居家", "balletcore home wrap warmers", "专属美学"),
    I("quiet_luxury", "克制老钱", "quiet luxury distance desire", "专属美学"),
    I("songchi", "松弛感", "songchi relaxed real wrinkles", "专属美学"),
    I("yugai", "欲盖弥彰", "half-cover clutch shirt", "专属美学"),
    I("hk_neon", "港风霓虹窗", "HK neon window seepage", "专属美学"),
    I("heya", "日系部屋着", "jp heya-wear indoor casual", "专属美学"),
    I("broken_pure", "纯欲破碎", "broken pure soft empty eyes", "专属美学"),
    I("cream_home", "奶油风房间", "cream room soft life", "专属美学"),
]

# ── 专属 Erotic ─────────────────────────────────────────────────
EROTIC_INTENSITY = [
    I("soft", "软色情", "soft sensual lean", "专属尺度"),
    I("sensual", "情色", "sensual half-nude ok", "专属尺度"),
    I("explicit", "大胆explicit★", "explicit anatomy connection ok", "专属尺度"),
    I("max", "最色拉满", "max open wet peak", "专属尺度"),
]
EROTIC_ACT = [
    I("solo-display", "自展★", "solo open display", "专属行为"),
    I("masturbation", "自慰", "masturbation hand or toy", "专属行为"),
    I("caught", "被撞见", "caught half-undressed", "专属行为"),
    I("voyeur", "偷窥感", "voyeur door gap composition", "专属行为"),
    I("exhibition", "暴露半公开", "exhibition risk environment", "专属行为"),
    I("foreplay", "前戏", "foreplay kiss hands", "专属行为"),
    I("oral", "口交类", "oral act", "专属行为"),
    I("bj", "含/口交", "lips around shaft", "专属行为"),
    I("deepthroat", "深喉", "lips to base tears optional", "专属行为"),
    I("cunnilingus", "舔阴", "face between thighs", "专属行为"),
    I("titjob", "乳交", "shaft between breasts", "专属行为"),
    I("handjob", "手交", "hands on shaft", "专属行为"),
    I("footjob", "足交", "feet arch on shaft", "专属行为"),
    I("intercourse", "插入做爱", "intercourse junction written", "专属行为"),
    I("anal", "肛交点名", "anal entry user-requested", "专属行为"),
    I("missionary", "传教士", "missionary legs open", "专属体位"),
    I("cowgirl", "骑乘", "cowgirl straddle hips down", "专属体位"),
    I("reverse_cowgirl", "反骑", "reverse cowgirl look back", "专属体位"),
    I("doggy", "后入", "doggy ass up arched", "专属体位"),
    I("prone_bone", "趴入", "prone bone hips raised", "专属体位"),
    I("spoon", "侧入", "spoon side-lying intimate", "专属体位"),
    I("standing", "站立", "standing wall one leg", "专属体位"),
    I("lotus", "坐抱", "lotus face-to-face seated", "专属体位"),
    I("mating_press", "折叠压", "mating press knees chest", "专属体位"),
    I("against_glass", "贴窗", "against glass city bokeh", "专属体位"),
    I("full_nelson", "全尼尔森点名", "full nelson adult only", "专属体位"),
    I("afterglow", "事后", "afterglow spent sheets", "专属行为"),
    I("orgasm", "高潮定格", "orgasm freeze", "专属行为"),
]
EROTIC_EXPOSURE = [
    I("e0", "E0 穿衣情欲", "clad erotic fabric cling", "专属E"),
    I("e1", "E1 半褪★", "half-undressed heights written", "专属E"),
    I("e2", "E2 内衣★", "lingerie worn detailed", "专属E"),
    I("e3", "E3 外翻拨开", "bra everted fabric aside still worn", "专属E"),
    I("e4", "E4 全裸", "fully nude optional prop", "专属E"),
]
EROTIC_FINISH = [
    I("none", "无体液结局★", "no finish fluids", "专属结局"),
    I("creampie", "中出", "creampie overflow junction", "专属结局"),
    I("facial", "颜射", "facial ropes face lashes", "专属结局"),
    I("body_shot", "外射身上", "cum on body glossy", "专属结局"),
    I("bukkake", "多人对颜", "multiple strands group context", "专属结局"),
    I("squirt", "潮吹", "squirt spray soaked sheets", "专属结局"),
    I("slick", "爱液滴", "slick drip viscous string", "专属结局"),
    I("saliva", "涎丝", "saliva string chin wet", "专属结局"),
]
EROTIC_DYNAMIC = [
    I("equal", "对等", "equal mutual desire", "专属权力"),
    I("dom_male", "男主", "male dominant grip hair waist", "专属权力"),
    I("femdom", "女主", "femdom command gaze", "专属权力"),
    I("bondage", "束缚", "bondage rope clear beautiful", "专属权力"),
    I("collar", "项圈牵引", "collar leash direction", "专属权力"),
    I("service", "侍奉", "service kneeling", "专属权力"),
    I("free_use", "自由使用氛围", "free-use relaxed available adult fiction", "专属权力"),
    I("cuckold_view", "绿帽视角", "cuckold viewer composition", "专属权力"),
]
EROTIC_FANTASY = [
    I("none", "纯现实F0★", "no fantasy", "专属幻想"),
    I("tentacle_caress", "触手爱抚", "elegant sensual tentacles caress", "专属幻想"),
    I("tentacle_sex", "触手插入点名", "tentacle penetration user-requested", "专属幻想"),
    I("lust_runes", "淫纹", "glowing lust runes lower belly", "专属幻想"),
    I("magic_bind", "光带缚", "magic light ribbons bind open", "专属幻想"),
    I("succubus", "魅魔", "succubus horns tail wings adult", "专属幻想"),
    I("slime", "史莱姆", "translucent slime face clear", "专属幻想"),
    I("fox_spirit", "狐妖", "fox spirit multi-tail adult", "专属幻想"),
    I("catgirl", "猫耳", "cat ears tail adult face", "专属幻想"),
    I("elf", "精灵", "elf pointed ears adult", "专属幻想"),
    I("time_stop", "时停", "time-stop ambient frozen others", "专属幻想"),
    I("invisible", "隐形人", "invisible partner pressure marks", "专属幻想"),
    I("android", "机械姬", "android seam lights interface", "专属幻想"),
]
EROTIC_BODYFOCUS = [
    I("face", "脸眼", "face eyes wet priority", "专属焦点"),
    I("breasts", "胸", "breasts shape light", "专属焦点"),
    I("ass", "臀", "ass up angle", "专属焦点"),
    I("pussy", "穴", "sex open wet", "专属焦点"),
    I("penis", "根", "shaft hardness junction", "专属焦点"),
    I("full", "全身连接", "full body junction readable", "专属焦点"),
    I("feet", "足", "feet arch", "专属焦点"),
    I("hands", "手", "hands spreading or bound", "专属焦点"),
    I("belly", "小腹", "belly tension soft", "专属焦点"),
    I("junction", "结合部", "wet junction priority", "专属焦点"),
]


def subject_dict() -> dict:
    return {
        "eth": ETH,
        "age": AGE,
        "body": BODY,
        "sex": SEX,
        "cast": CAST,
        "hair": HAIR,
    }


def public_lists() -> dict:
    return {
        "pose": POSE,
        "cloth": CLOTH,
        "prop": PROP,
        "set": SET,
        "light": LIGHT,
        "cam": CAM,
        "makeup": MAKEUP,
        "expr": EXPR,
        "grade": GRADE,
    }
